stages:
  - tagging

variables:
  REGISTRY: registry.flinkwork.com

before_script:
  - export CI_PUSH_REPO=https://albert_automat:xFraNxeurCicNySBqrzs@git.flinkwork.com/apps/ticketteer-website.git
  - echo $CI_PUSH_REPO
  - echo "Starting scripts $(date)"
  - echo "WORKING DIRECTORY $(pwd) with USER $(whoami)"

# tagcomplete:
#   image: registry.flinkwork.com/docker:latest
#   stage: tagging
#   script:
#     - echo "all good. Version ${VERSION} is tagged and ready."
#   only:
#     - /^[\d]{1,3}\.[\d]{1,3}\.[\d]{1,3}/

tag:
  image: registry.flinkwork.com/apps/ticketteer-website:core
  stage: tagging
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - git config --global user.email "albert_automat@flinkwork.com"
    - git config --global user.name "Albert Automat"
    - cd /app
    # - git pull --tags $CI_PUSH_REPO
    # - export CUR_VERSION="$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))"
    # - echo "CUR VERSION is ${CUR_VERSION}"
    # - export VERSION=$(bash ./increment_version.sh -p ${CUR_VERSION})
    # - echo "Version is ${VERSION}"
    # - printf "${VERSION}build$(date +%Y-%m-%dT%H:%M:%S)" > ./VERSION
    # - docker build -t ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest .
    # - docker run --name www-tmp-build ${REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest npm run build
    # - docker cp www-tmp-build:/app/public .
    # - docker rm -v www-tmp-build
    - ls -lah node_modules/gatsby
    - ./node_modules/gatsby/dist/bin/gatsby.js build
    - ls -lah
    - git add .
    # - git commit -am "release ${VERSION}"
    # - git tag -a ${VERSION} -m "release ${VERSION}"
    # - git push --tags $CI_PUSH_REPO
    - chmod 0400 ./id_rsa
    - scp -i ./id_rsa -o StrictHostKeyChecking=No -r ./public/* ubuntu@n.ticketteer.com:/var/www/html/
  only:
    - master@apps/ticketteer-website
