version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: phoos8dai0Maipheifaidei6
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: phoos8dai0Maipheifaidei6

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - $PWD:/var/www/
    ports:
      - "8010:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: phoos8dai0Maipheifaidei6
      WORDPRESS_DB_NAME: wordpress

volumes:
    db_data: {}
