version: "3"

services:

  app:
    build: .
    image: registry.flinkwork.com/apps/ticketteer-website:0.0.0
    command: npm run build
    volumes:
      - ./src:/app/src
      - ./html:/app/public
      - node_modules
    environment:
      NODE_ENV: production
